name: mtg_archiver
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  # https://pub.dev/packages/connectivity_plus
  connectivity_plus: ^5.0.2

  # https://pub.dev/packages/cupertino_icons
  cupertino_icons: ^1.0.6

  # https://pub.dev/packages/dio
  dio: ^5.4.0

  flutter:
    sdk: flutter

  # https://pub.dev/packages/flutter_dotenv
  flutter_dotenv: ^5.1.0

  # https://pub.dev/packages/flutter_riverpod
  flutter_riverpod: ^2.4.10

  # https://pub.dev/packages/freezed_annotation
  freezed_annotation: ^2.4.1

  # https://pub.dev/packages/riverpod_annotation
  riverpod_annotation: ^2.3.4

dev_dependencies:

  # https://pub.dev/packages/build_runner
  build_runner: ^2.4.8

  flutter_test:
    sdk: flutter

  # https://pub.dev/packages/flutter_lints
  flutter_lints: ^3.0.1

  # https://pub.dev/packages/freezed
  freezed: ^2.4.7

  # https://pub.dev/packages/json_serializable
  json_serializable: ^6.7.1

  # https://pub.dev/packages/riverpod_generator
  riverpod_generator: ^2.3.11

flutter:

  uses-material-design: true

  assets:
    - assets/cfg/app_settings

  generate: false


